#ifndef	VERSION_INCLUDED
#define VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define VERSION_MAJOR	1
#define VERSION_MINOR	0
#define VERSION_PATCH	0
#define VERSION_BETA	0
#define VERSION_VERSTRING	MAKE_STR(VERSION_MAJOR) "." MAKE_STR(VERSION_MINOR) "." MAKE_STR(VERSION_PATCH) "." MAKE_STR(VERSION_BETA)

#endif
